export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_LOADING = "AUTH_LOGIN_LOADING";
export const AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGOUT_LOADING = "AUTH_LOGIN_LOADING";
export const AUTH_LOGOUT_FAILED = "AUTH_LOGIN_FAILED";

